# ==================================== tidb conf  ==========================================
spring:
  profiles:
    active: dev
  application:
    name: metis-storage

# ==================================== conf for mybatis =====================================
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.platon.metis.storage.dao.entity

