spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.120.136:3306/metis_storage?useSSL=false&useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: ENC(HkIWS/Vhu9RkQsS542nJeQ==)
      password: ENC(bWqYB1AVri0/bQrC7ta4IZme9ib22Bge)

grpc:
  server:
    port: 9090
